# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'community_sample (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for community_sample (iOS)
  pod 'KakaoSDKCommon'  # 필수 요소를 담은 공통 모듈
  pod 'KakaoSDKAuth'  # 사용자 인증
  pod 'KakaoSDKUser'  # 카카오 로그인, 사용자 관리

  pod 'Firebase/Analytics'
  pod 'Firebase/Firestore'
end

target 'community_sample (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for community_sample (macOS)

end
